name: Deploy frontend on the S3 bucket and serve it via CDN

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the latest code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./Frontend

      - name: Build the code
        run: npm run build
        working-directory: ./Frontend

      - name: Save the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buzzbuddy-build
          path: ./Frontend/dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync ./Frontend/dist s3://imalokk-buzzbuddy --delete